---
title: "R Notebook"
output: html_notebook
---
Tarea 3
Estudiante:Carlos Daniel Oxom Coy


2. Utilice operadores lógicos (& and |), según corresponda:





```{r}

dataset_results <- read.csv("primary_results.csv")

#1. Filtrar todos los votos del estado de Florida
florida_votes <- filter(dataset_results, state == "Florida") #1. Filtrar todos los votos del estado de Florida.'

#2.1. Filtrar votos para los candidatos Hillary Clinton o Donald Trump
clinton_or_trump <- filter(dataset_results, candidate == "Hillary Clinton" | candidate == "Donald Trump")

#2.2. Filtrar votos para el partido Demócrata y el condado Shelby
democrat_and_shelby <- filter(dataset_results, county == "Shelby" & party == "Democrat")

#2.3. Filtrar votos para el estado de Alabama y que la cantidad de votos sea mayor a 15000.
alabama_15000 <- filter(dataset_results, state == "Alabama" & votes >= 15000)

florida_votes
clinton_or_trump
democrat_and_shelby
alabama_15000

```
```{r}
#3.1. Filtrar votos para el estado de Texas y el condado Denton, #seleccionando
#únicamente las columnas party, candidate, votes, luego ordene de forma
#descendente por la columna votes.

texas_data <- filter(dataset_results, state == "Texas")

denton_data <- filter(texas_data, county == "Denton")
denton_data_selected <- select(denton_data, party, candidate, votes)
denton_data_arranged <- arrange(denton_data_selected, desc(votes))
                            
denton_data_arranged


```
```{r}
#4.1. Filtrar por el partido Republicano, que el candidato sea Ted Cruz en el #estado de
#Alaska, luego agregue una columna que se llame vote_count que sea la #división de
#votes por fraction_votes (votes/fraction_votes), finalmente ordene de forma
#descendente por vote_count.


ted_cruz_alaska <- filter(dataset_results, party == "Republican" & candidate == "Ted Cruz" & state == "Alaska")
ted_cruz_alaska

ted_mutated <- mutate(ted_cruz_alaska, vote_count=votes/fraction_votes)
ted_mutated

ted_arranged <- arrange(ted_mutated, desc(vote_count))
ted_arranged



```

